name: Latest blog post length
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Insatall jq
        run: sudo apt install -y jq
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "Updated readme with the latest blogposts"
          feed_list: "https://esteetey.dev/rss.xml"
          max_post_count: 1000
          output_only: true
      - name: Saves count as an output
        id: count-step
        run: echo "::set-output name=articles_length::$(jq '. | length' /tmp/blog_post_workflow_output.json)"
      - name: Prints count
        run: echo ${{ steps.count-step.outputs.articles_length }}
 
